# Generated by Django 3.0.5 on 2020-04-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('title', models.CharField(max_length=30)),
                ('about', models.TextField(blank=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='side_image')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='gallery')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Image3')),
                ('title1', models.CharField(max_length=30)),
                ('title2', models.CharField(max_length=30)),
                ('title3', models.CharField(max_length=30)),
                ('description1', models.CharField(max_length=120)),
                ('description2', models.CharField(max_length=120)),
                ('description3', models.CharField(max_length=120)),
                ('hiwImage1', models.ImageField(blank=True, null=True, upload_to='hiwImage1')),
                ('hiwImage2', models.ImageField(blank=True, null=True, upload_to='hiwImage2')),
                ('hiwImage3', models.ImageField(blank=True, null=True, upload_to='hiwImage3')),
                ('hiwtitle1', models.CharField(max_length=30)),
                ('hiwtitle2', models.CharField(max_length=30)),
                ('hiwtitle3', models.CharField(max_length=30)),
                ('hiwdescription1', models.CharField(max_length=120)),
                ('hiwdescription2', models.CharField(max_length=120)),
                ('hiwdescription3', models.CharField(max_length=120)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='side_image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('project_area', models.CharField(max_length=50)),
                ('description', models.TimeField()),
                ('task', models.TimeField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_image')),
                ('project_image1', models.ImageField(blank=True, null=True, upload_to='project_image1')),
                ('project_image2', models.ImageField(blank=True, null=True, upload_to='project_image2')),
                ('project_image3', models.ImageField(blank=True, null=True, upload_to='project_image3')),
            ],
        ),
    ]
