# Generated by Django 3.0.5 on 2020-04-03 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200403_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='task_choices',
            field=models.CharField(choices=[('DE', 'Design'), ('BU', 'Build'), ('CO', 'Concept'), ('DB', 'Design & Build')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
